### ISSUE TITLE
Archives are not created

### ISSUE THREAD

**Issue by KIRUYXAN** [syorito-hatsuki/ducky-updater-rework#14]
I have “fileAction”: “ARCHIVE”, but the archive with old mods is not created, only the old file with .prepair.json where the names of the removed mods are

**Comment by syorito-hatsuki** [comment]
> I have “fileAction”: “ARCHIVE”, but the archive with old mods is not created, only the old file with .prepair.json where the names of the removed mods are

Archive will be created after restart. If you remove old mods on the fly then the server can crash

**Comment by KIRUYXAN** [comment]
but I have a client

**Comment by syorito-hatsuki** [comment]
> but I have a client

Same as on the client, after you restart the client it will archive them. (At least should)

**Comment by KIRUYXAN** [comment]
no, even after restarting it did not create the archive

**Comment by KIRUYXAN** [comment]
I found such an error and apparently it does not create an archive because of : in the title

[17:42:26] [DefaultDispatcher-worker-1/ERROR]: Uncaught exception in thread "DefaultDispatcher-worker-1"
net.lingala.zip4j.exception.ZipException: java.io.FileNotFoundException: C:\Users\KIRUYXAN\AppData\Roaming\.minecraft\mods\old\DURW [2024-06-30 17:42:26].zip (Синтаксическая ошибка в имени файла, имени папки или метке тома)
	at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:58) ~[net_lingala_zip4j_zip4j-2.11.5-85e16124d5907c0a.jar:?]
	at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:45) ~[net_lingala_zip4j_zip4j-2.11.5-85e16124d5907c0a.jar:?]
	at net.lingala.zip4j.ZipFile.addFiles(ZipFile.java:319) ~[net_lingala_zip4j_zip4j-2.11.5-85e16124d5907c0a.jar:?]
	at net.lingala.zip4j.ZipFile.addFile(ZipFile.java:263) ~[net_lingala_zip4j_zip4j-2.11.5-85e16124d5907c0a.jar:?]
	at dev.syoritohatsuki.duckyupdaterrework.core.util.FileActions.archiveOldMods(FileActions.kt:57) ~[DuckyUpdaterRework%20v2024.5.4.jar:?]
	at dev.syoritohatsuki.duckyupdaterrework.core.util.FileActions.run(FileActions.kt:46) ~[DuckyUpdaterRework%20v2024.5.4.jar:?]
	at dev.syoritohatsuki.duckyupdaterrework.DuckyUpdaterReWork$onInitialize$1.invokeSuspend(DuckyUpdaterReWork.kt:31) ~[DuckyUpdaterRework%20v2024.5.4.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[org_jetbrains_kotlin_kotlin-stdlib-2.0.0-e823d47a24b16be4.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException
Caused by: java.io.FileNotFoundException: C:\Users\KIRUYXAN\AppData\Roaming\.minecraft\mods\old\DURW [2024-06-30 17:42:26].zip (Синтаксическая ошибка в имени файла, имени папки или метке тома)
	at java.io.RandomAccessFile.open0(Native Method) ~[?:?]
	at java.io.RandomAccessFile.open(RandomAccessFile.java:344) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:259) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:213) ~[?:?]
	at net.lingala.zip4j.io.outputstream.SplitOutputStream.<init>(SplitOutputStream.java:51) ~[net_lingala_zip4j_zip4j-2.11.5-85e16124d5907c0a.jar:?]
	at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFilesToZip(AbstractAddFileToZipTask.java:66) ~[net_lingala_zip4j_zip4j-2.11.5-85e16124d5907c0a.jar:?]
	at net.lingala.zip4j.tasks.AddFilesToZipTask.executeTask(AddFilesToZipTask.java:33) ~[net_lingala_zip4j_zip4j-2.11.5-85e16124d5907c0a.jar:?]
	at net.lingala.zip4j.tasks.AddFilesToZipTask.executeTask(AddFilesToZipTask.java:20) ~[net_lingala_zip4j_zip4j-2.11.5-85e16124d5907c0a.jar:?]
	at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:51) ~[net_lingala_zip4j_zip4j-2.11.5-85e16124d5907c0a.jar:?]
	... 14 more

**Comment by syorito-hatsuki** [comment]
And windows again...🥲

**Comment by syorito-hatsuki** [comment]
> Author

https://github.com/syorito-hatsuki/ducky-updater-rework/issues/13#issuecomment-2219296526

**Comment by syorito-hatsuki** [comment]
Try a new update and reopen the issue if required
https://modrinth.com/mod/ducky-updater-rework/version/2024.7.1
