### ISSUE TITLE
Newest update crashes my game

### ISSUE THREAD

**Issue by Dootama** [syorito-hatsuki/ducky-updater-rework#3]
The newest version of this mod crashes my game when I try to open worlds and servers, it's likely some compatibility thing but idk. I'll include my mod list and the crash note

![Screenshot (10)](https://github.com/syorito-hatsuki/ducky-updater/assets/138728098/1a777c0a-d07e-4662-8e25-a8cfc95a5c66)
yeah ik, I have a lot of mods

-1
no idea what that means but apparently it's the exit code

[crash-2023-07-13_13.24.46-client.txt](https://github.com/syorito-hatsuki/ducky-updater/files/12042538/crash-2023-07-13_13.24.46-client.txt)

**Comment by syorito-hatsuki** [comment]
1. You installed Library, not mod.
2.  Crash happen at `Lnet/minecraft/entity/Entity;getX()D`. My mod or Lib doesn't have any communication with that class and method.

**Comment by Dootama** [comment]
I had the mod installed when it was crashing, I just had to remove it from my folder to get the game to run so I could figure out what mod was doing it

**Comment by syorito-hatsuki** [comment]
> I had the mod installed when it was crashing, I just had to remove it from my folder to get the game to run so I could figure out what mod was doing it

In log what u send u used lib. And I didn't update the mod up to a few months

**Comment by Dootama** [comment]
Okay my bad, the newest update to the lib still crashes my game when I open a world or server. It makes no sense to me.

Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_23317()" because "$$0" is null
Idk if this helps

**Comment by syorito-hatsuki** [comment]
> 

I tried a locally identical pack but without ElytraPhysics. I didn't find it.
My launcher (Prism) gave me better log. And that line it Xaero Minimap error

Our logs
```java
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_23317()" because "$$0" is null
	at net.minecraft.class_2784.method_11979(class_2784.java:274)
	at net.minecraft.class_329.method_1735(class_329.java:1082)
	at net.minecraft.class_329.method_1753(class_329.java:168)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

My logs
```java
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_23317()" because "entity" is null
	at xaero.common.minimap.waypoints.render.WaypointsIngameRenderer.render(WaypointsIngameRenderer.java:121)
	at xaero.common.core.XaeroMinimapCore.beforeIngameGuiRender(XaeroMinimapCore.java:203)
	at net.minecraft.class_329.handler$deh000$xaerominimap$onRenderStart(class_329.java:5898)
	at net.minecraft.class_329.method_1753(class_329.java)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

We can see that this part is identical.
```java
        at net.minecraft.class_329.method_1753(class_329.java)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

And upper we see this two
```java
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_23317()" because "entity" is null
	at xaero.common.minimap.waypoints.render.WaypointsIngameRenderer.render(WaypointsIngameRenderer.java:121)
	at xaero.common.core.XaeroMinimapCore.beforeIngameGuiRender(XaeroMinimapCore.java:203)
```

I already added to issue list that lib crash. But you logs not part of that crash

**Comment by syorito-hatsuki** [comment]
https://github.com/syorito-hatsuki/ducky-updater-lib/issues/4
