### ISSUE TITLE
Something with Kotlin [CRASH]

### ISSUE THREAD

**Issue by KiloTheNeko** [syorito-hatsuki/ducky-updater-rework#6]
[latest.log](https://github.com/syorito-hatsuki/ducky-updater/files/13062983/latest.log)

the server only crashed after Ducky Updater was included

for the specific element
```
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]
Caused by: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at dev.syoritohatsuki.duckyupdater.command.DuckyUpdaterCommandsKt.serverSideCommands(DuckyUpdaterCommands.kt) ~[ducky-updater-2023.6.1-1.20.jar:?]
	at net.minecraft.class_2170.handler$zkk000$ducky-updater$addCommands(class_2170.java:1024) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:267) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:73) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:944) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 3 more
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at dev.syoritohatsuki.duckyupdater.command.DuckyUpdaterCommandsKt.serverSideCommands(DuckyUpdaterCommands.kt) ~[ducky-updater-2023.6.1-1.20.jar:?]
	at net.minecraft.class_2170.handler$zkk000$ducky-updater$addCommands(class_2170.java:1024) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:267) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:73) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:944) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 3 more
```

that is part of the crash log that came after the 'minecraft has crashed' message though i included the full crash log in case its something with another mod being incompatible 😄

**Comment by syorito-hatsuki** [comment]
Fixed in https://github.com/syorito-hatsuki/ducky-updater-rework/pull/10, soon will be uploaded to Modrinth and CurseForge
