### ISSUE TITLE
Got an Error, ISE

### ISSUE THREAD

**Issue by suerion** [syorito-hatsuki/ducky-updater-rework#8]
Hey, i had got an Illegal State Exception from Ducky Updater.

```
[12:41:08] [Thread-2/ERROR]: Uncaught exception in thread "Thread-2"
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.Gson.fromJson(Gson.java:1226) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1124) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1001) ~[gson-2.10.jar:?]
        at dev.syoritohatsuki.duckyupdater.DuckyUpdater.requestUpdatesFromApi(DuckyUpdater.kt:135) ~[ducky-updater-2023.6.1-1.20.jar:?]
        at dev.syoritohatsuki.duckyupdater.DuckyUpdater.checkForUpdate(DuckyUpdater.kt:55) ~[ducky-updater-2023.6.1-1.20.jar:?]
        at net.minecraft.class_2966.md59296c$ducky-updater$lambda$requestUpdates$0$0(class_2966.java:1016) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[gson-2.10.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:182) ~[gson-2.10.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
        ... 7 more
```

**Comment by syorito-hatsuki** [comment]
Fixed in https://github.com/syorito-hatsuki/ducky-updater-rework/pull/10, soon will be uploaded to Modrinth and CurseForge
